language: python
python:
- '2.7'
- '3.4'
- '3.5'

addons:
  apt:
    packages:
    - libgdal1h
    - gdal-bin
    - libgdal-dev
    - swig
    - g++-4.8-multilib

install:
- pip install numpy
- pip install git+git://github.com/gipit/gippy.git@develop
- pip install -e .

script:
- python setup.py nosetests
