language: python
python:
- '2.7'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libgdal1h
    - gdal-bin
    - libgdal-dev
    - swig
    - g++-4.8

install:
- export CXX="g++-4.8" CC="gcc-4.8"
- pip install --upgrade pip
- pip install numpy==1.9.1
- pip install git+git://github.com/gipit/gippy.git@lib_compile
- pip install -e .

script:
- python setup.py nosetests
